# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sujin Jang
title: Ph.D. Student
email: sujin.jang@kaist.ac.kr
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  sujin0529
instagram_username: sujin1156
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: /images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Sujin Jang.
  I am a member of [ProsysLab](https://prosys.kaist.ac.kr/) advised by [Kihong Heo](https://kihongheo.kaist.ac.kr/)

  My research interests are as follows:
  - Program Synthesis
  - Automated Software Testing
  - Program Analysis

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: KAIST
        caption: Sep. 2024 -
        sub_title: Ph.D.
        quote: >
          KAIST - Korea Advanced Institute of Science and Technology
        description: | # this will include new lines to allow paragraphs
          Graduate School of Information Security
    
      - layout: left
        title: KAIST
        caption: Mar. 2022 - Aug. 2024
        sub_title: M.S.
        quote: >
          KAIST - Korea Advanced Institute of Science and Technology
        description: | # this will include new lines to allow paragraphs
          Graduate School of Information Security

      - layout: left
        title: CNU
        caption: Mar. 2018 - Feb. 2022
        sub_title: B.S.
        quote: >
          CNU - Chungnam National University
        description: | # this will include new lines to allow paragraphs
          Computer Science and Engineering
          
          I was a member of [ARGOS](https://argos.or.kr/), security club.

  - title: Publications # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      <li>
        UnitCon: Synthesizing Targeted Unit Tests for Java Runtime Exceptions

        <b>Sujin Jang</b>, Yeonhee Ryou, Heewon Lee, and Kihong Heo

        ACM International Conference on the Foundations of Software Engineering (FSE), 2025
      </li>
    
  - title: Awards # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Teaching Assistant
        description: |
            Outstanding Teaching Assistant Award, School of Computing, KAIST (Fall 2024)

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Teaching Assistant
        caption: Sep. 2022 -
        quote: >
          at KAIST, Korea
        description: | # this will include new lines to allow paragraphs
            CS524: Program Analysis (Spring 2025)
            
            CS424: Program Reasoning (Fall 2022, Fall 2024)
            
            CS348: Introduction to Information Security (Spring 2023)
      - layout: left
        title: Undergraduate Research Student
        caption: Apr. 2020 - Dec. 2021
        quote: >
          at Information Security Lab., Chungnam National University, Korea
        description: | # this will include new lines to allow paragraphs
            Study heap exploit.

            Research on command transmission using Bluetooth and Wi-Fi.
      - layout: left
        title: Teaching Assistant
        caption: Sep. 2019 - Dec. 2019
        quote: >
          at Chungnam National University, Korea
        description: | # this will include new lines to allow paragraphs
            Coding Basics for Problem solving.
      - layout: left
        title: Tutoring
        caption: Sep. 2019 - Dec. 2019
        quote: >
          at Chungnam National University, Korea
        description: | # this will include new lines to allow paragraphs
            Coached freshman on studying linear algebra.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Debugging Website
        caption: (Jan. 2020, 3-person project)
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Illustrates the debugging process of the program on the website.

          Implemented in JavaScript.

          Programmed analyzing and processing tokens in code.

#      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
